#!/bin/bash
i=0
grep="";
while [ "$grep" != "Starting user code" ] ;
do
        grep=`java -jar firmware/uniflash.jar vex ./bin/output.bin -PCOM3 | tee /dev/tty | grep "Starting user code"`;
        let i=i+1;
        echo "--------Attempt $i--------"
        if [ "$i" == "$1" ];
        then
			grep="Starting user code"
			echo "WARNING: All $i attempts exhausted!"
		fi
done
